config/routes.rb
Antlr::Application.routes.draw do
  resources :fan_pages 
  get 'fan_pages/:id/toggle_primary', :controller => 'fan_pages', :action => 'toggle_primary'  
  devise_for :users
  
  root :to => 'fan_pages#index'
  

end

app/models/fan_page.rb
class FanPage < ActiveRecord::Base
  #Associations
  belongs_to :user
  
  #validations
  validates :url, :presence => true
  
  validates :url, :uniqueness => { :scope => :user_id,
      :notice => "Already added this page" }
  
  #scopes
  default_scope :order => 'updated_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  #Associations
  has_many :fan_pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fan_pages_controller.rb
class FanPagesController < ApplicationController
  before_filter :authenticate_user!
  
  def toggle_primary
    user = current_user
    @fan_pages = FanPage.find_all_by_user_id(user.id)
    @fan_pages.each do |p|
      p.update_attributes(:primary => FALSE)
    end
    @fan_page = FanPage.find(params[:id])
    @fan_page.toggle!(:primary)
    respond_to do |format|
      flash[:success] = "Primary Page Changed"
      format.html { redirect_to root_path }
      format.js { @fan_pages = FanPage.find_all_by_user_id(user.id) }
    end
  end
  # GET /fan_pages
  # GET /fan_pages.json
  def index
    # unless params[:fan_page].nil? 
    #     response = HTTParty.get("https://graph.facebook.com/#{params[:fan_page][:url]}")  
    #     if response.code = "404"||"80"
    #       redirect_to '/fan_pages', notice: 'Bad URL'
    #       @fan_page = ""
    #        else  
    #    
    #     @fan_page = FanPage.new(
    #        :name => response['name'],
    #        :user_id => current_user.id,
    #        :primary => FALSE,
    #        :url => response['link'])
    #      end
    #    else
    #      
    #   end
      @fan_page = FanPage.new
    #   
    @user = current_user
    @fan_pages = @user.fan_pages 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fan_pages }
    end
  end

  # GET /fan_pages/1
  # GET /fan_pages/1.json
  def show
    @fan_page = FanPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fan_page }
    end
  end

  # GET /fan_pages/new
  # GET /fan_pages/new.json
  def new
    @fan_page = FanPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fan_page }
    end
  end

  # GET /fan_pages/1/edit
  def edit
    @fan_page = FanPage.find(params[:id])
  end

  # POST /fan_pages
  # POST /fan_pages.json
  def create
    url = params[:fan_page][:url]
    @url = url.gsub(/ /,'')
    response = HTTParty.get("https://graph.facebook.com/#{@url}")  
    code = response.code
    @fan_page = FanPage.new(
       :name => response['name'],
       :user_id => current_user.id,
       :primary => FALSE,
       :url => response['link'])
    
    respond_to do |format|
      if @fan_page.save
        format.html { redirect_to '/fan_pages', notice: 'Page Added Successfully' }
        format.json { render json: @fan_page, status: :created, location: @fan_page }
        format.js
      else
        @alert = 'Bad URL or Page already added'
        format.html { redirect_to '/fan_pages', alert: 'Bad URL or Page already added' }
        format.json { render json: @fan_page.errors, status: :unprocessable_entity }
        format.js { render 'failed.js', alert: 'Bad URL or Page already added' }
      end
    end
end

  # PUT /fan_pages/1
  # PUT /fan_pages/1.json
  def update
    @fan_page = FanPage.find(params[:id])

    respond_to do |format|
      if @fan_page.update_attributes(params[:fan_page])
        format.html { redirect_to @fan_page, notice: 'Fan page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fan_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fan_pages/1
  # DELETE /fan_pages/1.json
  def destroy
    @fan_page = FanPage.find(params[:id])
    @fan_page.destroy

    respond_to do |format|
      format.html { redirect_to fan_pages_url }
      format.js   
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fan_pages_helper.rb
module FanPagesHelper
end

app/views/fan_pages/_fan_page.html.erb
	<div id="fan_page">
		<ul>
	<li>
		<span><%= fan_page.name %></span><%= fan_page.url %>
		<p><%= link_to 'Remove', fan_page, method: :delete, :remote => true, :class => 'remove', :confirm => 'Are you sure?' %> 
			<span><%if fan_page.primary? %> Primary
		          <% else %><%= link_to 'Make Primary', {:action => :toggle_primary, :id => fan_page.id},  :remote => true %><% end %>
		    </span></p>
	</li>
	</ul>
	
	</div>

app/views/fan_pages/_form.html.erb
		<dl>
			<dt class="padded"><label for="facebook">Social Accounts</label></dt>
			<dd>
<%= form_for @fan_page, :remote => true do |f| %>

<span>facebook.com/</span>
  <input id="facebook" tabindex="3">
    <%= f.text_field(:url, :size => 10) %>
  </input>
  <button action="submit">Add</button>
<% end %>

app/views/fan_pages/edit.html.erb
<h1>Editing fan_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @fan_page %> |
<%= link_to 'Back', fan_pages_path %>

app/views/fan_pages/failed.js.erb
$('#alert').html("<%= escape_javascript raw('Bad URL or Page already added. Try a different URL') %>");
$('#new_fan_page')[0].reset()
$('#notice').html("<%= escape_javascript raw('') %>");

app/views/fan_pages/index.html.erb
<div class="wrapper">
<nav>
	<ul>
		<li class="current"><a href="#jumpBasic">Basic Information</a></li>
		<li><a href="#jumpDesign">Design</a></li>
		<li><a href="#jumpConfig">Configuration</a></li>
		<li><button>Save</button></li>
	</ul>
</nav>
</div>
<div id="content">
<div class="wrapper content">
	<section id="basic">
		<h1><img src="/null.png" id="jumpBasic" alt="" />Basic Information</h1>
		
				<%= render 'form' %>
				<p id="notice"><%= notice %></p>
				<p id="alert" style="color:red;padding-left:30px;"><%= alert %></p>
				<ul id="pages">
				<%= render @fan_pages %>
</ul>
			<dd>
				<span>twitter.com/</span><input type="text" id="twitter" tabindex="4" /><button>Add</button>
				<ul>
					<li>
						<div>
							<a href="#" class="remove" style="background-position:top right;padding-right:14px;" title="Remove this account from the list">X</a>
						</div>
						<span>PepsiCo</span>twitter.com/PepsiCo<br />
						<p><a href="#">Remove</a></p>
					</li>
				</ul>
			</dd>
		</dl>
	</section>
<hr />

</div>

app/views/fan_pages/new.html.erb
<h1>New fan_page</h1>

<%= render 'form' %>

<%= link_to 'Back', fan_pages_path %>

app/views/fan_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fan_page.name %>
</p>

<p>
  <b>Url:</b>
  <%= @fan_page.url %>
</p>

<p>
  <b>Primary:</b>
  <%= @fan_page.primary %>
</p>

<p>
  <b>User:</b>
  <%= @fan_page.user_id %>
</p>


<%= link_to 'Edit', edit_fan_page_path(@fan_page) %> |
<%= link_to 'Back', fan_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Antlr</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="wrapper">
			<ul id="breadcrumbs">
				<li class="logo"><a href="/"><img src="/antlr.png" alt="Antlr" /></a></li>
				<li><a href="/">&larr; Back to Home</a></li>
						<%= render 'devise/menu/registration_items' %>
			</ul>
		</div>
	</header>

<%= yield %>
	
</body>
</html>